spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
security:
  basic:
    enabled: false
